import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AppShell, Card, Empty, Heading, Stat } from '@/components/app-shell';
import { TrendChart } from '@/components/charts';
import { farmContext, date, money, number, sum } from '@/lib/farm';
export const dynamic='force-dynamic';
export default async function Lot({params}:{params:Promise<{id:string}>}){
 const {id}=await params;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();const {db,farm}=await farmContext();const [lotResult,animalResult,weightResult,costResult]=await Promise.all([db.from('lotes').select('*').eq('id',id).eq('fazenda_id',farm.id).eq('sistema','corte').maybeSingle(),db.from('animais').select('*').eq('fazenda_id',farm.id).eq('lote_id',id),db.from('pesagens').select('*').eq('fazenda_id',farm.id).eq('lote_id',id).order('data_pesagem'),db.from('transacoes').select('tipo,valor').eq('fazenda_id',farm.id).eq('lote_id',id)]);
 if([lotResult,animalResult,weightResult,costResult].some(x=>x.error))throw new Error('Falha ao carregar lote');const lot=lotResult.data;if(!lot)notFound();const animals=(animalResult.data||[]).filter(x=>x.status==='ativo'),weights=weightResult.data||[],costs=(costResult.data||[]).filter(x=>x.tipo==='despesa'),latest=weights.at(-1),previous=weights.at(-2);const days=previous&&latest?(new Date(latest.data_pesagem).getTime()-new Date(previous.data_pesagem).getTime())/86400000:0;const gmd=latest&&previous&&days>0?(Number(latest.peso_kg)-Number(previous.peso_kg))/days:null;const entered=lot.data_entrada?Math.max(0,Math.floor((Date.now()-new Date(`${lot.data_entrada}T12:00:00`).getTime())/86400000)):null;const meta=lot.peso_meta==null?null:Number(lot.peso_meta);const toGoal=meta!=null&&latest&&gmd!=null&&gmd>0?Math.max(0,Math.ceil((meta-Number(latest.peso_kg))/gmd)):null;const headCount=animals.length||latest?.quantidade_animais||null;const costPerHead=costs.length&&headCount?sum(costs,'valor')/headCount:null;
 return <AppShell farm={farm} active="Rebanho"><Link href="/painel/rebanho" className="back-link">← Rebanho</Link><Heading eyebrow="Detalhe do lote" title={lot.nome}/><p className="section-note">{lot.categoria||'Categoria não informada'} · {animals.length} animais vinculados</p><div className="stat-grid"><Stat label="Peso médio registrado" value={latest?`${number(Number(latest.peso_kg),1)} kg`:'—'} detail="Última pesagem do lote"/><Stat label="Peso total estimado" value={latest&&headCount?`${number(Number(latest.peso_kg)*headCount,1)} kg`:'—'} detail="Peso médio × animais informados"/><Stat label="GMD" value={gmd!=null?`${number(gmd,2)} kg/dia`:'—'} detail="Entre duas últimas pesagens"/><Stat label="Custo por cabeça" value={money(costPerHead)} detail="Despesas vinculadas / animais"/><Stat label="Custo por arroba produzida" value={gmd!=null&&days>0&&headCount&&costs.length&&gmd>0?money(sum(costs,'valor')/((Number(latest?.peso_kg)-Number(previous?.peso_kg))*headCount/15)):'—'} detail="Somente com ganho e custos medidos"/><Stat label="Dias no sistema" value={entered==null?'—':entered}/><Stat label="Meta de peso" value={meta==null?'—':`${number(meta,1)} kg`}/><Stat label="Projeção até a meta" value={toGoal==null?'—':`${toGoal} dias`} detail="Se o GMD atual for mantido"/></div><Card title="Evolução do peso médio"><TrendChart points={weights.slice(-16).map(x=>({label:date(x.data_pesagem).slice(0,5),value:Number(x.peso_kg)}))} unit="kg"/></Card><Card title="Projeção econômica"><div className="stat-grid"><Stat label="Custo futuro" value="—" detail="Requer custo diário do lote"/><Stat label="Valor estimado de venda" value="—" detail="Requer preço de venda registrado"/><Stat label="Lucro projetado" value="—" detail="Requer preço e custos futuros"/></div><p className="section-note">As projeções financeiras só aparecerão quando houver dados suficientes para calculá-las.</p></Card><Card title="Animais do lote">{animals.length?animals.map(x=><div className="data-row" key={x.id}><strong>{x.nome||x.identificacao}</strong><span>{x.identificacao}</span></div>):<Empty title="Nenhum animal vinculado" description="Ao cadastrar um animal, selecione este lote." href="/painel/rebanho"/>}</Card><Link className="primary-link" href="/painel/novo/pesagem">+ Registrar pesagem</Link></AppShell>;
}
