import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AppShell, Heading } from '@/components/app-shell';
import { Icon } from '@/components/icons';
import { createAnimal, createLot, createMilk, createStock, createWeighing } from '@/app/actions';
import { farmContext } from '@/lib/farm';
export const dynamic='force-dynamic';
const titles:Record<string,string>={corte:'Animal de corte',leite:'Vaca leiteira',lote:'Novo lote',pesagem:'Nova pesagem',producao:'Produção de leite',estoque:'Novo item de estoque'};
const paths:Record<string,string>={corte:'rebanho',leite:'leite',lote:'rebanho',pesagem:'pesagens',producao:'leite',estoque:'estoque'};
const currentDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default async function NewRecord({params}:{params:Promise<{tipo:string}>}) {
 const {tipo}=await params;if(!titles[tipo])notFound();const {db,farm}=await farmContext();
 const [lotsResult,animalsResult]=await Promise.all([db.from('lotes').select('id,nome').eq('fazenda_id',farm.id).eq('sistema','corte').eq('ativo',true),db.from('animais').select('id,identificacao,nome,sistema').eq('fazenda_id',farm.id).eq('status','ativo')]);
 if(lotsResult.error||animalsResult.error)throw new Error('Não foi possível carregar os registros.');
 const lots=lotsResult.data||[],animals=animalsResult.data||[],dairy=animals.filter(x=>x.sistema==='leite'),beef=animals.filter(x=>x.sistema!=='leite');
 const animal=tipo==='corte'||tipo==='leite',milk=tipo==='leite';
 return <AppShell farm={farm} active={milk||tipo==='producao'?'Leite':tipo==='corte'||tipo==='lote'?'Rebanho':''}><Link className="back-link" href={`/painel/${paths[tipo]}`}><Icon name="back" size={18}/> Voltar para {paths[tipo]==='rebanho'?'Corte':paths[tipo]}</Link><Heading eyebrow={`Novo registro · ${milk||tipo==='producao'?'Leite':'Fazenda Varela'}`} title={titles[tipo]}/>
 <section className="form-page"><div className="form-intro"><span><Icon name={animal?'herd':tipo==='lote'?'box':tipo==='pesagem'?'scale':tipo==='producao'?'milk':'box'} size={25}/></span><div><strong>{animal?'Dados do animal':tipo==='lote'?'Dados do lote':tipo==='pesagem'?'Acompanhar peso':tipo==='producao'?'Registro de leite':'Insumo da fazenda'}</strong><p>{animal?'Preencha as informações disponíveis. Os campos sem dados podem ficar vazios.':'Os registros serão salvos na Fazenda Varela.'}</p></div></div>
 {animal ? <form action={createAnimal} className="entry-form"><input type="hidden" name="modulo" value={milk?'leite':'corte'}/><div className="form-section-title">IDENTIFICAÇÃO</div><div className="form-grid"><label>Brinco / identificação *<input name="identificacao" required maxLength={80} placeholder={milk?'LEITE-001':'BRINCO-001'}/></label><label>Nome (opcional)<input name="nome" maxLength={120} placeholder="Nome do animal"/></label></div>
 <div className="form-grid">{milk?<label>Situação<select name="situacao_leite"><option>Em lactação</option><option>Seca</option><option>Prenhe</option><option>Descartada</option></select></label>:<label>Categoria<select name="categoria"><option>Novilha</option><option>Bezerro</option><option>Boi</option><option>Touro</option><option>Vaca de corte</option><option>Outra</option></select></label>}<label>Raça<input name="raca" placeholder={milk?'Girolando':'Nelore'}/></label></div>
 {milk?<input name="categoria" type="hidden" value="Vaca leiteira"/>:<div className="form-grid"><label>Sexo<select name="sexo"><option value="">Não informado</option><option value="F">Fêmea</option><option value="M">Macho</option></select></label><label>Situação<select name="status"><option value="ativo">Ativo</option><option value="vendido">Vendido</option><option value="abatido">Abatido</option><option value="morto">Morto</option></select></label></div>}
 <div className="form-section-title">{milk?'SAÚDE E PRODUÇÃO':'PESO E ORIGEM'}</div><div className="form-grid"><label>Data de nascimento<input name="data_nascimento" type="date"/></label><label>{milk?'Peso (kg)':'Peso de entrada (kg)'}<input name="peso_entrada" type="number" min="0" step="0.01"/></label></div><div className="form-grid"><label>Peso atual (kg)<input name="peso_atual" type="number" min="0" step="0.01"/></label>{milk?<label>Último parto<input name="data_ultimo_parto" type="date"/></label>:<label>Data de entrada<input name="data_entrada" type="date"/></label>}</div>
 {milk?<div className="form-grid"><label>Próximo parto previsto<input name="proxima_previsao_parto" type="date"/></label><label>Bezerro relacionado<select name="bezerro_id"><option value="">Nenhum</option>{dairy.map(x=><option key={x.id} value={x.id}>{x.nome||x.identificacao}</option>)}</select></label></div>:<><div className="form-grid"><label>Lote<select name="lote_id"><option value="">Sem lote</option>{lots.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label>Origem<input name="origem" placeholder="Fazenda de origem"/></label></div><label>Valor de compra (R$)<input name="valor_compra" type="number" min="0" step="0.01"/></label></>}
 <label>Foto do animal (opcional)<input name="foto" type="file" accept="image/jpeg,image/png,image/webp,image/heic"/><small>Até 4 MB. Fotos são privadas e acessíveis apenas à sua conta.</small></label><label>Observações<textarea name="observacoes" rows={3} placeholder="Detalhes que você queira lembrar"/></label><button type="submit">Salvar {milk?'vaca leiteira':'animal de corte'} <Icon name="arrow" size={19}/></button></form>
 :tipo==='lote'?<form action={createLot} className="entry-form"><label>Nome do lote *<input name="nome" required maxLength={120} placeholder="Ex.: Novilhas 2026"/></label><div className="form-grid"><label>Categoria<input name="categoria" placeholder="Recria, engorda..."/></label><label>Meta de peso (kg)<input name="peso_meta" type="number" min="0" step="0.01"/></label></div><button>Criar lote <Icon name="arrow" size={18}/></button></form>
 :tipo==='pesagem'?<form action={createWeighing} className="entry-form"><label>Lote ou animal *<select name="target" required><option value="">Selecione</option>{lots.map(x=><option key={x.id} value={`l:${x.id}`}>Lote: {x.nome}</option>)}{beef.map(x=><option key={x.id} value={`a:${x.id}`}>Animal: {x.nome||x.identificacao}</option>)}</select></label><div className="form-grid"><label>Data<input name="data_pesagem" type="date" defaultValue={currentDate()} required/></label><label>Peso (kg)<input name="peso_kg" type="number" min="0.01" step="0.01" required/></label></div><label>Quantidade de animais (se for lote)<input name="quantidade_animais" type="number" min="1"/></label><button>Salvar pesagem <Icon name="arrow" size={18}/></button></form>
 :tipo==='producao'?<form action={createMilk} className="entry-form"><label>Origem da produção<select name="animal_id"><option value="">Total do tanque / rebanho</option>{dairy.map(x=><option key={x.id} value={x.id}>{x.nome||x.identificacao}</option>)}</select></label><div className="form-grid"><label>Data<input name="data_producao" type="date" defaultValue={currentDate()} required/></label><label>Litros<input name="litros" type="number" min="0.01" step="0.01" required/></label></div><div className="form-grid"><label>Turno<select name="turno"><option value="total_dia">Total do dia</option><option value="manha">Manhã</option><option value="tarde">Tarde</option><option value="noite">Noite</option></select></label><label>Preço por litro (R$)<input name="preco_litro" type="number" min="0" step="0.01"/></label></div><button>Salvar produção <Icon name="arrow" size={18}/></button></form>
 :<form action={createStock} className="entry-form"><label>Nome do item *<input name="nome" required placeholder="Ex.: Sal proteinado"/></label><div className="form-grid"><label>Categoria<select name="categoria"><option>Ração</option><option>Suplementação</option><option>Silagem</option><option>Medicamentos</option><option>Combustível</option><option>Outros</option></select></label><label>Unidade<input name="unidade" defaultValue="kg" required/></label></div><div className="form-grid"><label>Quantidade<input name="quantidade_atual" type="number" min="0" step="0.01" required/></label><label>Estoque mínimo<input name="estoque_minimo" type="number" min="0" step="0.01"/></label></div><label>Consumo médio por dia<input name="consumo_medio_dia" type="number" min="0" step="0.01"/></label><button>Cadastrar item <Icon name="arrow" size={18}/></button></form>}
 </section></AppShell>;
}
