import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {AppShell,Card,Empty,Heading,Stat} from '@/components/app-shell';
import {TrendChart} from '@/components/charts';
import {AnimalActions} from '@/components/management-actions';
import {ExitForm} from '@/components/corte-forms';
import {animalRelations} from '@/lib/related-records';
import {date,farmContext,money,number} from '@/lib/farm';
import {exitEconomics,weightStats} from '@/lib/corte';
import {saveDairyPregnancy,updateDairyCalf,registerDairyCalfWeight,transferDairyCalfToBeef} from '@/app/actions';
import {diasEntre,hojeNaFazenda,idadeLegivel} from '@/lib/reproducao';
export const dynamic='force-dynamic';
export default async function Animal({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{acao?:string;status?:string;aba?:string;tipo?:string;erro?:string;salvo?:string}>}){
 const {id}=await params,q=await searchParams;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();const {db,farm}=await farmContext();
 const [a,w,m,t,h,s]=await Promise.all([
  db.from('animais').select('*').eq('id',id).eq('fazenda_id',farm.id).maybeSingle(),
  db.from('pesagens').select('*').eq('animal_id',id).eq('fazenda_id',farm.id).order('data_pesagem'),
  db.from('producao_leite').select('*').eq('animal_id',id).eq('fazenda_id',farm.id).order('data_producao'),
  db.from('transacoes').select('*').eq('animal_id',id).eq('fazenda_id',farm.id),
  db.from('manejos').select('*').eq('animal_id',id).eq('fazenda_id',farm.id).order('data_manejo',{ascending:false}),
  db.from('saidas_corte').select('*').eq('animal_id',id).eq('fazenda_id',farm.id).maybeSingle()
 ]);if([a,w,m,t,h,s].some(r=>r.error))throw new Error('Falha ao carregar animal');if(!a.data)notFound();
 const animal=a.data,dairy=animal.sistema==='leite',isCalf=dairy&&animal.categoria==='Cria leiteira',weights=w.data||[],health=h.data||[],costs=t.data||[],exit=s.data;
 const [offspringResult,birthsResult,motherResult]=dairy?await Promise.all([
   isCalf?Promise.resolve({data:[],error:null}):db.from('animais').select('*').eq('fazenda_id',farm.id).eq('mae_id',id).order('data_nascimento',{ascending:false}),
   isCalf?Promise.resolve({data:[],error:null}):db.from('partos_leite').select('*').eq('fazenda_id',farm.id).eq('mae_id',id).order('data_parto',{ascending:false}),
   isCalf&&animal.mae_id?db.from('animais').select('id,identificacao,nome,data_ultimo_parto').eq('id',animal.mae_id).eq('fazenda_id',farm.id).maybeSingle():Promise.resolve({data:null,error:null}),
 ]):[{data:[],error:null},{data:[],error:null},{data:null,error:null}];
 if(offspringResult.error||birthsResult.error||motherResult.error)throw new Error('Falha ao carregar reprodução');
 const children=offspringResult.data||[],births=birthsResult.data||[],mother=motherResult.data,currentCalf=children.find(c=>c.status==='ativo'&&c.situacao_cria==='mamando');
 const {data:birthCalves,error:birthCalvesError}=births.length?await db.from('crias_parto_leite').select('*').eq('fazenda_id',farm.id).in('parto_id',births.map(b=>b.id)): {data:[],error:null};
 if(birthCalvesError)throw new Error('Falha ao carregar histórico de partos');
 const [lots,relations]=dairy?[[],null] as const:await Promise.all([db.from('lotes').select('id,nome,peso_meta').eq('fazenda_id',farm.id).eq('sistema','corte').then(r=>{if(r.error)throw new Error('Lotes indisponíveis');return r.data||[]}),q.acao==='excluir'?animalRelations(db,id,farm.id):Promise.resolve(null)]);
 const goal=lots.find(l=>l.id===animal.lote_id)?.peso_meta,stats=weightStats(animal,weights,goal),economics=exit?exitEconomics(animal,exit,costs):null;
 const image=animal.foto_url?await db.storage.from('fotos-animais').createSignedUrl(animal.foto_url,3600):null;
 const section=['pesagens','sanidade','saida'].includes(q.aba||'')?q.aba:'pesagens';
 return <AppShell farm={farm} active={dairy?'Leite':'Rebanho'}><Link href={dairy?'/painel/leite':'/painel/rebanho'} className="back-link">← {dairy?'Leite':'Corte'}</Link><Heading eyebrow="Ficha individual" title={String(animal.nome||animal.identificacao)}/><p className="section-note">{animal.identificacao} · {animal.categoria||'Categoria não informada'} · {animal.status}</p>
 {q.salvo&&<p role="status" className="app-notice good">Registro salvo.</p>}{q.erro&&<p role="alert" className="app-notice bad">Não foi possível concluir. Confira os dados.</p>}
 {!dairy&&<AnimalActions animal={animal} lots={[...lots]} relations={relations} action={q.acao} status={q.status} error={q.erro}/>}
 {image?.data?.signedUrl&&<div className="animal-portrait"><Image src={image.data.signedUrl} alt={`Foto de ${animal.identificacao}`} fill unoptimized sizes="(max-width: 600px) 100vw, 750px"/></div>}
 <div className="stat-grid"><Stat label={exit?'Peso final':'Peso atual'} value={exit?.peso_final!=null?`${number(Number(exit.peso_final),1)} kg`:stats.current!=null?`${number(stats.current,1)} kg`:'—'}/><Stat label="Peso de entrada" value={animal.peso_entrada!=null?`${number(Number(animal.peso_entrada),1)} kg`:'—'}/><Stat label="GMD recente" value={stats.recentGmd!=null?`${number(stats.recentGmd,2)} kg/dia`:'—'}/><Stat label="Valor de compra" value={money(animal.valor_compra)}/></div>
 <Card title="Identificação"><div className="detail-grid"><span>Brinco<strong>{animal.identificacao}</strong></span><span>Raça<strong>{animal.raca||'—'}</strong></span><span>Sexo<strong>{animal.sexo==='femea'?'Fêmea':animal.sexo==='macho'?'Macho':'—'}</strong></span><span>Entrada<strong>{animal.data_entrada?date(animal.data_entrada):'—'}</strong></span><span>Lote<strong>{lots.find(l=>l.id===animal.lote_id)?.nome||'—'}</strong></span><span>Origem<strong>{animal.origem||'—'}</strong></span></div>{animal.observacoes&&<p className="section-note">{animal.observacoes}</p>}</Card>
 {dairy?<>
 {isCalf?<>
 <Card title="Mãe & nascimento"><div className="detail-grid"><span>Mãe<strong>{mother?<Link href={`/animais/${mother.id}?aba=reproducao`}>{mother.nome||mother.identificacao} →</Link>:'Não informada'}</strong></span><span>Nascimento<strong>{animal.data_nascimento?date(animal.data_nascimento):'—'}</strong></span><span>Idade<strong>{animal.data_nascimento?idadeLegivel(animal.data_nascimento):'—'}</strong></span><span>Pai/touro<strong>{animal.pai_touro||'—'}</strong></span><span>Situação<strong>{animal.situacao_cria||'—'}</strong></span><span>Desmame<strong>{animal.data_desmame?date(animal.data_desmame):'—'}</strong></span></div></Card>
 <Card title="Crescimento & pesagens"><div className="stat-grid"><Stat label="Peso ao nascer" value={animal.peso_entrada!=null?`${number(Number(animal.peso_entrada),1)} kg`:'—'}/><Stat label="Peso atual" value={animal.peso_atual!=null?`${number(Number(animal.peso_atual),1)} kg`:'—'}/></div><TrendChart points={weights.map(x=>({label:date(x.data_pesagem).slice(0,5),value:Number(x.peso_kg)}))} unit="kg"/>{weights.map(x=><div className="data-row" key={x.id}><strong>{date(x.data_pesagem)}</strong><span>{number(Number(x.peso_kg),1)} kg</span></div>)}{animal.status==='ativo'&&<form action={registerDairyCalfWeight} className="inline-form"><input type="hidden" name="cria_id" value={id}/><label>Data<input type="date" name="data_pesagem" max={hojeNaFazenda()} required/></label><label>Peso atual (kg)<input name="peso_kg" type="number" min="0.01" step="0.01" required/></label><button type="submit">Registrar peso</button></form>}</Card>
 <Card title="Situação & desmame"><form action={updateDairyCalf} className="entry-form"><input type="hidden" name="cria_id" value={id}/><div className="form-grid"><label>Nome<input name="nome" defaultValue={animal.nome||''}/></label><label>Raça<input name="raca" defaultValue={animal.raca||''}/></label></div><div className="form-grid"><label>Situação<select name="situacao_cria" defaultValue={animal.situacao_cria||'mamando'}>{[['mamando','Mamando'],['desmamada','Desmamada'],['vendida','Vendida'],['transferida','Transferida'],['morta','Morta'],['natimorta','Natimorta']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Pai / touro<input name="pai_touro" defaultValue={animal.pai_touro||''}/></label></div><div className="form-grid"><label>Data do desmame<input type="date" name="data_desmame" defaultValue={animal.data_desmame||''}/></label><label>Desmame previsto<input type="date" name="data_prevista_desmame" defaultValue={animal.data_prevista_desmame||''}/></label></div><label>Observações<textarea name="observacoes" rows={3} defaultValue={animal.observacoes||''}/></label><button type="submit">Salvar dados da cria</button></form></Card>
 {animal.status==='ativo'&&<Card title="Transferir para Corte"><p className="section-note">Esta ação é explícita: mantém o vínculo com a mãe e o histórico do parto, mas retira a cria dos indicadores do Leite. O animal passa ao Corte sem lote; escolha um lote depois.</p><form action={transferDairyCalfToBeef} className="inline-form"><input name="cria_id" type="hidden" value={id}/><label>Digite TRANSFERIR para confirmar<input name="confirmacao" required autoComplete="off"/></label><button type="submit">Transferir ao Corte</button></form></Card>}
 </>:<>
 <nav className="detail-tabs" aria-label="Seções da vaca"><Link aria-current={q.aba==='reproducao'?'page':undefined} href="?aba=reproducao#reproducao">Reprodução & crias</Link><Link href="/painel/novo/producao">Produção de leite</Link></nav>
 <section id="reproducao"><Card title="Gestação"><div className="stat-grid"><Stat label="Prenha" value={animal.prenhe?'Sim':'Não'}/><Stat label="Parto previsto" value={animal.proxima_previsao_parto?date(animal.proxima_previsao_parto):'—'}/><Stat label="Dias restantes" value={animal.prenhe&&animal.proxima_previsao_parto?diasEntre(hojeNaFazenda(),animal.proxima_previsao_parto)??'—':'—'}/><Stat label="Último parto" value={animal.data_ultimo_parto?date(animal.data_ultimo_parto):'—'}/><Stat label="Cria mamando agora" value={currentCalf?String(currentCalf.nome||currentCalf.identificacao):'—'}/></div>{currentCalf&&<Link className="text-link" href={`/animais/${currentCalf.id}`}>Abrir ficha da cria →</Link>}
 <form action={saveDairyPregnancy} className="entry-form"><input type="hidden" name="vaca_id" value={id}/><div className="form-grid"><label>Está prenha?<select name="prenhe" defaultValue={animal.prenhe?'sim':'nao'}><option value="nao">Não</option><option value="sim">Sim</option></select></label><label>Cobertura / inseminação<input name="data_cobertura" type="date" defaultValue={animal.data_cobertura||''}/></label></div><div className="form-grid"><label>Touro / sêmen (opcional)<input name="touro_semen" defaultValue={animal.touro_semen||''}/></label><label>Parto estimado<input name="proxima_previsao_parto" type="date" defaultValue={animal.proxima_previsao_parto||''}/></label></div><label>Observações da gestação<textarea name="observacoes_reproducao" rows={2} defaultValue={animal.observacoes_reproducao||''}/></label><button type="submit">Salvar gestação</button></form></Card>
 <Card title="Partos anteriores">{births.length?births.map(b=><div className="birth-history" key={b.id}><strong>{date(b.data_parto)} · {b.quantidade_crias} {b.quantidade_crias===1?'cria':'crias'}</strong><small>{b.tipo_parto||'Tipo de parto não informado'}{b.touro_semen?` · ${b.touro_semen}`:''}</small>{(birthCalves||[]).filter(c=>c.parto_id===b.id).map(c=><div className="data-row" key={c.id}><div><strong>{c.cria_id?<Link href={`/animais/${c.cria_id}`}>{c.nome||c.identificacao||'Cria'} →</Link>:c.nome||c.identificacao||'Cria sem brinco'}</strong><small>{c.sexo==='femea'?'Fêmea':c.sexo==='macho'?'Macho':'Sexo não informado'} · {c.situacao_ao_nascer} · {c.peso_nascer!=null?`${number(Number(c.peso_nascer),1)} kg`:'Peso não informado'}</small></div></div>)}</div>):<Empty title="Nenhum parto registrado" description="Registre um parto, inclusive antigo, sem perder o histórico."/>}{animal.status==='ativo'&&<Link className="module-action" href={`/painel/reproducao/parto?mae=${id}`}>+ Registrar parto</Link>}</Card>
 <Card title="Crias vinculadas">{children.length?children.map(c=><Link href={`/animais/${c.id}`} className="data-row" key={c.id}><div><strong>{c.nome||c.identificacao}</strong><small>{c.data_nascimento?date(c.data_nascimento):'Nascimento não informado'} · {c.situacao_cria||'Situação não informada'}</small></div><span>Ficha →</span></Link>):<Empty title="Nenhuma cria vinculada" description="Registre o parto ou cadastre uma cria já nascida."/>}<Link className="module-action" href={`/painel/reproducao/cria?mae=${id}`}>+ Cadastrar cria existente</Link></Card></section>
 <Card title="Produção individual"><TrendChart points={(m.data||[]).map(x=>({label:date(x.data_producao).slice(0,5),value:Number(x.litros)}))} unit="L"/>{m.data?.length?m.data.map(x=><div className="data-row" key={x.id}><strong>{number(Number(x.litros),1)} litros</strong><span>{date(x.data_producao)} · {x.turno||'—'}</span></div>):<Empty title="Sem produção individual" description="Vincule uma produção a esta vaca."/>}</Card>
 </>}</>:<>
 <nav className="detail-tabs" aria-label="Seções do animal">{[['pesagens','Pesagens'],['sanidade','Sanidade'],['saida','Saída / Fechamento']].map(([key,label])=><Link key={key} aria-current={section===key?'page':undefined} href={`?aba=${key}#detalhe`}>{label}</Link>)}</nav><section id="detalhe">
 {section==='pesagens'&&<><div className="stat-grid"><Stat label="Maior peso" value={stats.maximum!=null?`${number(stats.maximum,1)} kg`:'—'}/><Stat label="Ganho total" value={stats.gain!=null?`${number(stats.gain,1)} kg`:'—'}/><Stat label="Dias no sistema" value={stats.days??'—'}/><Stat label="Até a meta" value={stats.remaining!=null?`${number(stats.remaining,1)} kg`:'—'}/><Stat label="Meta atingida" value={stats.progress!=null?`${number(stats.progress,1)}%`:'—'}/><Stat label="Projeção de dias" value={stats.projectedDays??'—'}/></div><Card title="Histórico de pesagens"><TrendChart points={stats.entries.map(x=>({label:date(x.data_pesagem).slice(0,5),value:Number(x.peso_kg)}))} unit="kg"/>{[...stats.entries].reverse().map((x,i)=><div className="data-row" key={`${x.data_pesagem}-${i}`}><div><strong>{number(Number(x.peso_kg),1)} kg · {date(x.data_pesagem)}</strong><small>Ganho: {x.gain!=null?`${number(x.gain,1)} kg`:'—'} · GMD: {x.gmd!=null?`${number(x.gmd,2)} kg/dia`:'—'}{x.responsavel?` · ${x.responsavel}`:''}{x.observacoes?` · ${x.observacoes}`:''}</small></div></div>)}{!weights.length&&<Empty title="Sem pesagens" description="Registre o primeiro peso."/>}<Link className="module-action" href={`/painel/novo/pesagem?animal=${id}`}>+ Registrar pesagem</Link></Card></>}
 {section==='sanidade'&&<Card title="Histórico de sanidade">{health.length?health.map(x=><div className="data-row" key={x.id}><div><strong>{x.produto||x.tipo} · {date(x.data_manejo)}</strong><small>{x.tipo}{x.dose?` · ${x.dose} ${x.dose_unidade||''}`:''}{x.via_aplicacao?` · ${x.via_aplicacao}`:''}{x.proxima_data?` · Reforço ${date(x.proxima_data)}`:''}{x.data_fim_carencia?` · Carência até ${date(x.data_fim_carencia)}`:''}</small><small>{[x.motivo,x.frequencia,x.responsavel,x.observacoes].filter(Boolean).join(' · ')}</small></div></div>):<Empty title="Nenhum manejo" description="Vacinas e tratamentos aparecerão aqui."/>}<Link className="module-action" href={`/painel/sanidade?animal=${id}`}>+ Registrar manejo</Link></Card>}
 {section==='saida'&&<Card title={exit?'Fechamento do animal':'Registrar saída'}>{exit&&economics?<><p className="section-note">{exit.tipo} · {date(exit.data_saida)}{exit.comprador_destino?` · ${exit.comprador_destino}`:''}</p><div className="stat-grid">{[['Peso inicial',economics.initial!=null?`${number(economics.initial,1)} kg`:'—'],['Peso final',economics.final!=null?`${number(economics.final,1)} kg`:'—'],['Ganho total',economics.gain!=null?`${number(economics.gain,1)} kg`:'—'],['GMD do período',economics.gmd!=null?`${number(economics.gmd,2)} kg/dia`:'—'],['Dias no sistema',economics.days??'—'],['Custo de compra',money(economics.purchase)],['Custos vinculados',money(economics.linked)],['Custo total por cabeça',money(economics.total)],['Custo por kg ganho',money(economics.costPerKg)],['Custo por @ produzida',money(economics.costPerArroba)],['Receita',money(economics.revenue)],['Lucro / prejuízo',money(economics.profit)],['Margem',economics.margin!=null?`${number(economics.margin,1)}%`:'—'],['Retorno investido',economics.roi!=null?`${number(economics.roi,1)}%`:'—'],['Preço por kg',money(economics.priceKg)],['Preço por @',money(economics.priceArroba)]].map(([label,value])=><Stat key={String(label)} label={String(label)} value={value}/>)}</div><p className="section-note">Custos coletivos não são distribuídos automaticamente. Cálculos por arroba exigem rendimento de carcaça informado.</p></>:animal.status==='ativo'?<ExitForm animal={id} kind={q.tipo}/>:<p>Animal inativo. Reative antes de registrar saída.</p>}</Card>}
 </section></>}
 <Card title="Lançamentos associados">{costs.length?costs.map(x=><div className="data-row" key={x.id}><strong>{x.descricao}</strong><span>{x.tipo==='despesa'?'-':'+'}{money(Number(x.valor))}</span></div>):<Empty title="Sem lançamentos" description="Custos e receitas vinculados aparecerão aqui."/>}</Card>
 </AppShell>;
}
