import Link from 'next/link';
import { signOut } from '@/app/actions';
const nav=[['/painel','Início','⌂'],['/painel/rebanho','Rebanho','♧'],['/painel/financeiro','Financeiro','▤'],['/painel/leite','Leite','◒'],['/painel/mais','Mais','☷']];
export function AppShell({farm,active,children}:{farm:{nome:string;cidade:string|null;estado:string|null};active:string;children:React.ReactNode}) {
 return <div className="app"><header className="app-header"><Link href="/painel" className="identity"><span className="brand-symbol">✦</span><span><strong>Fazenda Varela <i>IA</i></strong><small>{farm.cidade || farm.nome} · {farm.estado || 'PA'}</small></span></Link><form action={signOut}><button className="header-exit" title="Sair da conta" type="submit">Sair ↗</button></form></header><main className="app-main">{children}</main><nav className="bottom-nav" aria-label="Navegação principal">{nav.map(([href,label,icon])=><Link key={href} href={href} aria-current={active===label?'page':undefined}><span className="nav-icon">{icon}</span><small>{label}</small></Link>)}<Link href="/painel/registrar" className="nav-add" aria-label="Registrar">+</Link></nav></div>;
}
export function Heading({eyebrow,title,aside}:{eyebrow:string;title:string;aside?:React.ReactNode}) { return <div className="page-heading"><div><p className="overline">{eyebrow}</p><h1>{title}</h1></div>{aside}</div>; }
export function Card({title,children,className=''}:{title?:string;children:React.ReactNode;className?:string}) { return <section className={`app-card ${className}`}>{title&&<h2>{title}</h2>}{children}</section>; }
export function Stat({label,value,detail,tone=''}:{label:string;value:string|number;detail?:string;tone?:string}) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>; }
export function Empty({title,description,href,label}:{title:string;description:string;href?:string;label?:string}) {return <div className="empty"><span className="empty-icon">✳</span><strong>{title}</strong><p>{description}</p>{href&&<Link className="text-link" href={href}>{label||'Adicionar registro'} →</Link>}</div>}
export function Bars({values,labels}:{values:number[];labels:string[]}) {if(!values.some(v=>v>0))return <Empty title="Sem dados para o gráfico" description="O gráfico aparecerá conforme você registrar informações."/>;const max=Math.max(...values,1);return <div className="bars" role="img" aria-label={labels.map((l,i)=>`${l}: ${values[i]}`).join(', ')}>{values.map((value,i)=><div key={i}><div className="bar-track"><span style={{height:`${Math.max(value>0?3:0,value/max*100)}%`}}/></div><small>{labels[i]}</small></div>)}</div>}
export function Notice({error,ok}:{error?:string;ok?:string}) {return <>{error&&<p role="alert" className="app-notice bad">Não foi possível salvar. Confira os campos e tente novamente.</p>}{ok&&<p role="status" className="app-notice good">Registro salvo com sucesso.</p>}</>}
