'use client';
import { useEffect, useRef, useState } from 'react';
import { Icon } from '@/components/icons';
type Message={role:'user'|'assistant';text:string;metric?:string;label?:string};
const suggestions=['Quem está mais longe da meta?','Qual novilha está mais atrasada?','Compare B189 e B205','Quanto produziu o tanque este mês?','Qual despesa foi maior?','Quais itens do estoque estão baixos?'];
export function AssistantChat({storageKey}:{storageKey:string}){
 const key=`fazenda-assistant:${storageKey}`;
 const [messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[note,setNote]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),end=useRef<HTMLDivElement>(null);
 const [autoVoice,setAutoVoice]=useState(false),[playing,setPlaying]=useState<number|null>(null),[audioReady,setAudioReady]=useState<number|null>(null);
 const history=useRef<Message[]>([]),busyRef=useRef(false),audio=useRef<HTMLAudioElement|null>(null),audioUrls=useRef<Map<number,string>>(new Map()),autoRef=useRef(false);
 const voiceContext=useRef<AudioContext|null>(null),voiceSource=useRef<AudioBufferSourceNode|null>(null);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'[]');if(Array.isArray(saved)){const valid=saved.filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.text==='string').slice(-30);setMessages(valid);history.current=valid}const enabled=localStorage.getItem(key+':audio')==='true';setAutoVoice(enabled);autoRef.current=enabled}catch{}},[key]);
 useEffect(()=>{history.current=messages;if(messages.length)try{sessionStorage.setItem(key,JSON.stringify(messages.slice(-30)))}catch{};end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,key]);
 useEffect(()=>()=>{recorder.current?.stream?.getTracks().forEach(t=>t.stop());audio.current?.pause();try{voiceSource.current?.stop()}catch{};void voiceContext.current?.close();audioUrls.current.forEach(url=>URL.revokeObjectURL(url))},[]);
 // O iPhone só libera áudio após um toque. Desbloqueamos o contexto no toque do microfone,
 // antes das chamadas assíncronas de transcrição, consulta e síntese de voz.
 function unlockVoice(){try{const context=voiceContext.current??new AudioContext();voiceContext.current=context;void context.resume().catch(()=>{});const silent=context.createBufferSource();silent.buffer=context.createBuffer(1,1,context.sampleRate);silent.connect(context.destination);silent.start()}catch{}}
 function stopAudio(){try{voiceSource.current?.stop()}catch{};voiceSource.current=null;audio.current?.pause();if(audio.current)audio.current.currentTime=0;setPlaying(null)}
 function toggleAuto(enabled:boolean){if(enabled)unlockVoice();autoRef.current=enabled;setAutoVoice(enabled);try{localStorage.setItem(key+':audio',String(enabled))}catch{};if(!enabled)stopAudio()}
 async function speak(value:string,index:number){if(playing===index){stopAudio();return}unlockVoice();stopAudio();setNote('Preparando a resposta em áudio…');try{let url=audioUrls.current.get(index);if(!url){const response=await fetch('/api/assistant/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value})});if(!response.ok){const result=await response.json();throw new Error(result.error||'Não foi possível gerar a voz.')}url=URL.createObjectURL(await response.blob());audioUrls.current.set(index,url)}setAudioReady(index);const context=voiceContext.current;if(context?.state==='running'){const encoded=await (await fetch(url)).arrayBuffer();const buffer=await context.decodeAudioData(encoded);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);source.onended=()=>{if(voiceSource.current===source){voiceSource.current=null;setPlaying(null)}};voiceSource.current=source;source.start();setPlaying(index);setNote('');return}if(!audio.current){audio.current=new Audio();audio.current.onended=()=>setPlaying(null)}audio.current.src=url;await audio.current.play();setPlaying(index);setNote('')}catch(e){setPlaying(null);setNote(e instanceof DOMException&&e.name==='NotAllowedError'?'O iPhone bloqueou o início automático. Toque em “Ouvir resposta” para reproduzir.':e instanceof Error?e.message:'Áudio pronto. Toque em reproduzir para ouvir.')}}
 async function ask(value:string){const question=value.trim();if(!question||busyRef.current)return;const previous=history.current.slice(-8),index=history.current.length+1;busyRef.current=true;setText('');setNote('');setBusy(true);setMessages(prev=>[...prev,{role:'user',text:question}]);try{
  const response=await fetch('/api/assistant/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:previous})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível consultar.');
  setMessages(prev=>[...prev,{role:'assistant',text:result.answer,metric:result.metric,label:result.label}]);
  if(autoRef.current)void speak(result.answer,index);
 }catch(e){setMessages(prev=>[...prev,{role:'assistant',text:e instanceof Error?e.message:'Não foi possível consultar.'}])}finally{busyRef.current=false;setBusy(false)}}
 async function transcribe(file:File){if(file.size<100||file.size>12_000_000){setNote('Áudio inválido ou longo demais.');return}busyRef.current=true;setBusy(true);setNote('Transcrevendo sua pergunta…');try{const body=new FormData();body.set('audio',file);const response=await fetch('/api/ai/transcribe',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha na transcrição.');const transcript=String(result.text||'').trim();setText(transcript);setNote(autoRef.current?'Pergunta transcrita. Consultando a fazenda…':'Confira a transcrição e toque em Perguntar.');busyRef.current=false;setBusy(false);if(autoRef.current&&transcript)void ask(transcript)}catch(e){setNote(e instanceof Error?e.message:'Falha na transcrição.');busyRef.current=false;setBusy(false)}}
 function clear(){stopAudio();audioUrls.current.forEach(url=>URL.revokeObjectURL(url));audioUrls.current.clear();setAudioReady(null);history.current=[];setMessages([]);sessionStorage.removeItem(key)}
 async function toggleMic(){unlockVoice();if(recording){recorder.current?.stop();setRecording(false);return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setNote('Use o ditado do teclado ou digite sua pergunta.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const format=['audio/mp4','audio/webm','audio/ogg'].find(x=>MediaRecorder.isTypeSupported(x));const rec=new MediaRecorder(stream,format?{mimeType:format}:undefined);recorder.current=rec;chunks.current=[];rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);void transcribe(new File(chunks.current,'pergunta',{type:rec.mimeType}))};rec.start();setRecording(true);setNote('Gravando. Toque novamente para terminar.')}catch{setNote('Permita o microfone no navegador ou digite sua pergunta.')}}
 return <div className="assistant-layout">
  <section className="assistant-hero"><span><Icon name="spark" size={21}/> INTELIGÊNCIA DA FAZENDA</span><h2>Converse com os dados da fazenda.</h2><p>Faça perguntas livres e continue a conversa. Consulto apenas os registros da sua conta, sem alterar nada.</p></section>
  <div className="assistant-pane">
   <div className="assistant-head"><div><strong>Conversa da Fazenda</strong><small>Somente leitura · dados da sua conta</small></div>{messages.length>0&&<button className="assistant-clear" type="button" onClick={clear}>Limpar conversa</button>}</div>
   <div className="assistant-stream" role="log" aria-live="polite">
    {messages.length===0?<div className="assistant-welcome"><span className="assistant-orb"><Icon name="spark" size={28}/></span><h3>O que você quer saber hoje?</h3><p>Você pode perguntar de outro jeito e fazer perguntas de acompanhamento. Se faltar informação, eu aviso.</p></div>:messages.map((m,i)=><div key={i} className={`assistant-message ${m.role}`}><span>{m.role==='user'?'VOCÊ':'ASSISTENTE'}</span>{m.metric&&<div className="assistant-number"><small>{m.label}</small><strong>{m.metric}</strong></div>}<p>{m.text}</p>{m.role==='assistant'&&<div className="assistant-voice-controls"><button type="button" onClick={()=>void speak(m.text,i)} aria-label={playing===i?'Parar áudio':audioReady===i?'Repetir áudio':'Ouvir resposta'}>{playing===i?'■ Parar áudio':audioReady===i?'↻ Repetir áudio':'▶ Ouvir resposta'}</button>{audioReady===i&&<audio src={audioUrls.current.get(i)} controls preload="none" aria-label="Áudio da resposta"/>}</div>}</div>)}
    {busy&&<p className="assistant-thinking" role="status">Consultando os registros…</p>}<div ref={end}/>
   </div>
   <label className="assistant-auto-voice"><input type="checkbox" checked={autoVoice} onChange={e=>toggleAuto(e.target.checked)}/><span>Responder por voz automaticamente<small>Ao falar pelo microfone, transcrevo e respondo em texto e áudio.</small></span></label>
   <div className="assistant-suggestions"><span>EXEMPLOS PARA COMEÇAR</span><div>{suggestions.map(q=><button key={q} type="button" disabled={busy} onClick={()=>void ask(q)}>{q} <span aria-hidden="true">↗</span></button>)}</div></div>
   <form className="assistant-composer" onSubmit={e=>{e.preventDefault();void ask(text)}}><label htmlFor="farm-question" className="sr-only">Pergunta sobre a fazenda</label><textarea id="farm-question" rows={2} maxLength={350} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask(text)}}} placeholder="Pergunte sobre sua fazenda…"/><div><button className={`assistant-mic ${recording?'recording':''}`} aria-label={recording?'Parar gravação':'Gravar pergunta'} title="Perguntar por voz" disabled={busy} type="button" onClick={()=>void toggleMic()}>{recording?'■':'🎙'}</button><button className="assistant-send" disabled={busy||recording||!text.trim()} type="submit">Perguntar <span aria-hidden="true">→</span></button></div></form>
   {note&&<p role="status" className="assistant-note">{note}</p>}<p className="assistant-privacy">O histórico fica neste navegador durante a sessão. O áudio da pergunta é transcrito e não fica armazenado.</p>
  </div>
 </div>;
}
