'use client';
import { useEffect, useRef, useState } from 'react';
import { Icon } from '@/components/icons';
type Message={role:'user'|'assistant';text:string;metric?:string;label?:string};
const suggestions=['Peso médio do Lote 1','Gastos do mês','Estoque baixo','Vacas perto de parir','Animais sem pesagem recente','Quem precisa de reforço de vacina?'];
export function AssistantChat({storageKey}:{storageKey:string}){
 const key=`fazenda-assistant:${storageKey}`;
 const [messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[note,setNote]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'[]');if(Array.isArray(saved))setMessages(saved.filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.text==='string').slice(-30))}catch{}},[key]);
 useEffect(()=>{if(messages.length)try{sessionStorage.setItem(key,JSON.stringify(messages.slice(-30)))}catch{};end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,key]);
 useEffect(()=>()=>{recorder.current?.stream?.getTracks().forEach(t=>t.stop())},[]);
 async function ask(value:string){const question=value.trim();if(!question||busy)return;setText('');setNote('');setBusy(true);setMessages(prev=>[...prev,{role:'user',text:question}]);try{
  const response=await fetch('/api/assistant/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível consultar.');
  setMessages(prev=>[...prev,{role:'assistant',text:result.answer,metric:result.metric,label:result.label}]);
 }catch(e){setMessages(prev=>[...prev,{role:'assistant',text:e instanceof Error?e.message:'Não foi possível consultar.'}])}finally{setBusy(false)}}
 async function transcribe(file:File){if(file.size<100||file.size>12_000_000){setNote('Áudio inválido ou longo demais.');return}setBusy(true);setNote('Transcrevendo sua pergunta…');try{const body=new FormData();body.set('audio',file);const response=await fetch('/api/ai/transcribe',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha na transcrição.');setText(result.text||'');setNote('Confira a transcrição e toque em Perguntar.')}catch(e){setNote(e instanceof Error?e.message:'Falha na transcrição.')}finally{setBusy(false)}}
 async function toggleMic(){if(recording){recorder.current?.stop();setRecording(false);return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setNote('Use o ditado do teclado ou digite sua pergunta.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const format=['audio/mp4','audio/webm','audio/ogg'].find(x=>MediaRecorder.isTypeSupported(x));const rec=new MediaRecorder(stream,format?{mimeType:format}:undefined);recorder.current=rec;chunks.current=[];rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);void transcribe(new File(chunks.current,'pergunta',{type:rec.mimeType}))};rec.start();setRecording(true);setNote('Gravando. Toque novamente para terminar.')}catch{setNote('Permita o microfone no navegador ou digite sua pergunta.')}}
 return <div className="assistant-layout"><section className="assistant-hero"><span><Icon name="spark" size={21}/> INTELIGÊNCIA DA FAZENDA</span><h2>Uma resposta clara para cada decisão.</h2><p>Pergunte sobre corte, leite, sanidade, finanças ou estoque. Consulto os registros da sua fazenda sem alterar nada.</p></section><div className="assistant-pane"><div className="assistant-head"><div><strong>Conversa da Fazenda</strong><small>Somente leitura · dados da sua conta</small></div>{messages.length>0&&<button className="assistant-clear" type="button" onClick={()=>{setMessages([]);sessionStorage.removeItem(key)}}>Limpar conversa</button>}</div><div className="assistant-stream" role="log" aria-live="polite">{messages.length===0?<div className="assistant-welcome"><span className="assistant-orb"><Icon name="spark" size={28}/></span><h3>O que você quer saber hoje?</h3><p>As respostas usam os registros existentes. Se faltar informação para um cálculo, eu aviso.</p></div>:messages.map((m,i)=><div key={i} className={`assistant-message ${m.role}`}><span>{m.role==='user'?'VOCÊ':'ASSISTENTE'}</span>{m.metric&&<div className="assistant-number"><small>{m.label}</small><strong>{m.metric}</strong></div>}<p>{m.text}</p></div>)}{busy&&<p className="assistant-thinking" role="status">Consultando os registros…</p>}<div ref={end}/></div><div className="assistant-suggestions"><span>EXPERIMENTE PERGUNTAR</span><div>{suggestions.map(q=><button key={q} type="button" disabled={busy} onClick={()=>void ask(q)}>{q} <span aria-hidden="true">↗</span></button>)}</div></div><form className="assistant-composer" onSubmit={e=>{e.preventDefault();void ask(text)}}><label htmlFor="farm-question" className="sr-only">Pergunta sobre a fazenda</label><textarea id="farm-question" rows={2} maxLength={350} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask(text)}}} placeholder="Pergunte sobre sua fazenda…"/><div><button className={`assistant-mic ${recording?'recording':''}`} aria-label={recording?'Parar gravação':'Gravar pergunta'} title="Perguntar por voz" disabled={busy} type="button" onClick={()=>void toggleMic()}>{recording?'■':'🎙'}</button><button className="assistant-send" disabled={busy||recording||!text.trim()} type="submit">Perguntar <span aria-hidden="true">→</span></button></div></form>{note&&<p role="status" className="assistant-note">{note}</p>}<p className="assistant-privacy">A conversa fica neste navegador durante a sessão. O áudio é transcrito e não é armazenado.</p></div></div>;
}
