import Link from 'next/link';
import {AppShell,Bars,Card,Empty,Heading,Stat} from '@/components/app-shell';
import {TrendChart} from '@/components/charts';
import {Icon} from '@/components/icons';
import {date,farmContext,milkDailyTotals,money,monthBounds,number} from '@/lib/farm';
import {diasEntre,hojeNaFazenda,idadeLegivel} from '@/lib/reproducao';

export const dynamic='force-dynamic';
export default async function DairyHome({searchParams}:{searchParams:Promise<{erro?:string;salvo?:string}>}){
 const flash=await searchParams,{db,farm}=await farmContext();
 const [m,a]=await Promise.all([db.from('producao_leite').select('*').eq('fazenda_id',farm.id).order('data_producao',{ascending:false}).limit(300),db.from('animais').select('*').eq('fazenda_id',farm.id).eq('sistema','leite').order('identificacao').limit(500)]);
 if(m.error||a.error)throw new Error('Não foi possível carregar o leite');
 const milk=m.data||[],animals=a.data||[],cows=animals.filter(x=>x.categoria!=='Cria leiteira'),calves=animals.filter(x=>x.categoria==='Cria leiteira');
 const {start,end,label}=monthBounds(),current=milk.filter(x=>x.data_producao>=start&&x.data_producao<end),daily=milkDailyTotals(current),liters=daily.reduce((n,x)=>n+x.liters,0);
 const revenue=current.filter(x=>x.preco_litro!=null).reduce((n,x)=>n+Number(x.litros)*Number(x.preco_litro),0),today=hojeNaFazenda();
 const pregnant=cows.filter(x=>x.status==='ativo'&&x.prenhe),lactating=cows.filter(x=>x.status==='ativo'&&String(x.situacao_leite||'').toLowerCase().includes('lact'));
 const upcoming=pregnant.filter(x=>x.proxima_previsao_parto&&diasEntre(today,x.proxima_previsao_parto)!==null&&diasEntre(today,x.proxima_previsao_parto)!<=30);
 return <AppShell farm={farm} active="Leite"><Heading eyebrow="FAZENDA VARELA IA · ATIVIDADE LEITEIRA" title="Leite"/>
 {flash.erro&&<p role="alert" className="app-notice bad">Não foi possível salvar o registro. Confira os dados.</p>}{flash.salvo&&<p role="status" className="app-notice good">Registro salvo.</p>}
 <section className="module-hero module-hero-milk"><span>PRODUÇÃO & MATERNIDADE</span><h2>O cuidado começa antes do primeiro litro.</h2><p>Produção, vacas e crias — tudo na atividade leiteira, separado do Corte.</p><Link href="/painel/novo/leite"><Icon name="plus" size={18}/> Vaca leiteira</Link></section>
 <div className="module-quick-actions"><Link className="module-action secondary" href="/painel/novo/producao"><Icon name="milk" size={18}/> Registrar leite</Link><Link className="module-action secondary" href="/painel/reproducao">Reprodução & crias →</Link></div>
 <p className="section-note">Atividade leiteira · {label}</p><div className="stat-grid"><Stat label="Vacas em lactação" value={lactating.length}/><Stat label="Vacas prenhas" value={pregnant.length}/><Stat label="Partos próximos" value={upcoming.length}/><Stat label="Crias mamando" value={calves.filter(x=>x.status==='ativo'&&x.situacao_cria==='mamando').length}/><Stat label="Crias desmamadas" value={calves.filter(x=>x.situacao_cria==='desmamada').length}/><Stat label="Produção do mês" value={current.length?`${number(liters,1)} L`:'—'}/><Stat label="Média diária" value={daily.length?`${number(liters/daily.length,1)} L`:'—'}/><Stat label="Receita estimada" value={current.some(x=>x.preco_litro!=null)?money(revenue):'—'}/></div>
 {pregnant.length>0&&<Card title="Próximos partos">{pregnant.slice(0,4).map(x=><Link className="data-row" key={x.id} href={`/animais/${x.id}?aba=reproducao`}><div><strong>{x.nome||x.identificacao}</strong><small>{x.proxima_previsao_parto?`Previsão ${date(x.proxima_previsao_parto)}`:'Previsão ainda não informada'}</small></div><span>{x.proxima_previsao_parto?`${diasEntre(today,x.proxima_previsao_parto)} dias`:'Completar →'}</span></Link>)}<Link className="module-action" href="/painel/reproducao">Ver reprodução e alertas</Link></Card>}
 <div className="two-col"><Card title="Produção diária"><TrendChart points={daily.slice(-20).map(x=>({label:x.day.slice(8),value:x.liters}))} unit="L"/></Card><Card title="Produção por vaca"><Bars values={cows.map(c=>current.filter(x=>x.animal_id===c.id).reduce((n,x)=>n+Number(x.litros),0)).filter(x=>x>0)} labels={cows.filter(c=>current.some(x=>x.animal_id===c.id)).map(c=>String(c.nome||c.identificacao))}/></Card></div>
 <Card title="Vacas leiteiras">{cows.length?cows.map(x=><Link href={`/animais/${x.id}?aba=reproducao`} className="data-row" key={x.id}><div><strong>{x.nome||x.identificacao}</strong><small>{x.identificacao} · {x.raca||'Raça não informada'} · {x.situacao_leite||'Situação não informada'}{x.prenhe?' · Prenha':''}</small></div><span>Ficha →</span></Link>):<Empty title="Nenhuma vaca cadastrada" description="Cadastre vacas leiteiras sem misturá-las ao gado de corte."/>}<Link className="module-action" href="/painel/novo/leite">+ Vaca leiteira</Link></Card>
 <Card title="Bezerros e bezerras">{calves.length?calves.slice(0,6).map(x=><Link href={`/animais/${x.id}`} className="data-row" key={x.id}><div><strong>{x.nome||x.identificacao}</strong><small>{x.data_nascimento?idadeLegivel(x.data_nascimento,today):'Idade não informada'} · {x.situacao_cria||'Situação não informada'}</small></div><span>Ficha →</span></Link>):<Empty title="Nenhuma cria cadastrada" description="Registre um parto ou cadastre bezerros já nascidos."/>}<Link className="module-action" href="/painel/reproducao">Ver crias & reprodução →</Link></Card>
 <Card title="Histórico de produção">{milk.length?milk.slice(0,25).map(x=><div className="data-row" key={x.id}><div><strong>{number(Number(x.litros),1)} litros</strong><small>{date(x.data_producao)} · {x.animal_id?cows.find(c=>c.id===x.animal_id)?.nome||cows.find(c=>c.id===x.animal_id)?.identificacao||'Vaca':'Tanque/rebanho'}</small></div><span>{x.preco_litro!=null?money(Number(x.litros)*Number(x.preco_litro)):'—'}</span></div>):<Empty title="Sem produção registrada" description="Registre leite por vaca ou pelo tanque."/>}</Card>
 </AppShell>;
}
