import Link from 'next/link';
import { AppShell, Card, Empty, Heading, Stat } from '@/components/app-shell';
import { Icon } from '@/components/icons';
import { MonthlyChart, TrendChart } from '@/components/charts';
import { farmContext, money, monthBounds, milkDailyTotals, number, sum } from '@/lib/farm';
export const dynamic='force-dynamic';
export default async function Dashboard(){
 const {db,farm}=await farmContext();const {start,end,label}=monthBounds();
 const [a,l,t,m,s,w]=await Promise.all([
 db.from('animais').select('id,valor_compra,status,sistema,criado_em').eq('fazenda_id',farm.id),
 db.from('lotes').select('id').eq('fazenda_id',farm.id).eq('sistema','corte').eq('ativo',true),
 db.from('transacoes').select('tipo,valor,status,categoria,data_competencia').eq('fazenda_id',farm.id).order('data_competencia',{ascending:false}).limit(500),
 db.from('producao_leite').select('litros,data_producao').eq('fazenda_id',farm.id).gte('data_producao',start).lt('data_producao',end),
 db.from('estoque').select('nome,quantidade_atual,estoque_minimo,consumo_medio_dia').eq('fazenda_id',farm.id).eq('ativo',true),
 db.from('pesagens').select('id,data_pesagem').eq('fazenda_id',farm.id).order('data_pesagem',{ascending:false}).limit(1)]);
 if([a,l,t,m,s,w].some(r=>r.error)) throw new Error('Não foi possível carregar os indicadores.');
 const all=(a.data||[]).filter(x=>x.status==='ativo'),beef=all.filter(x=>x.sistema!=='leite'),dairy=all.filter(x=>x.sistema==='leite'),tx=t.data||[],current=tx.filter(x=>x.data_competencia>=start&&x.data_competencia<end),income=current.filter(x=>x.tipo==='receita'),expense=current.filter(x=>x.tipo==='despesa');
 const pending=tx.filter(x=>x.tipo==='despesa'&&x.status!=='pago');const cash=tx.filter(x=>x.status==='pago').reduce((v,x)=>v+(x.tipo==='receita'?Number(x.valor):-Number(x.valor)),0);
 const valuation=beef.length&&beef.every(x=>x.valor_compra!=null)?sum(beef,'valor_compra'):null;
 const milkTotal=milkDailyTotals(m.data||[]).reduce((total,day)=>total+day.liters,0);
 const alerts=(s.data||[]).filter(x=>x.estoque_minimo!=null&&Number(x.quantidade_atual)<=Number(x.estoque_minimo));
 const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-(5-i));const key=d.toISOString().slice(0,7);const subset=tx.filter(x=>x.data_competencia?.startsWith(key));return {label:new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(d).replace('.',''),income:sum(subset.filter(x=>x.tipo==='receita'),'valor'),expense:sum(subset.filter(x=>x.tipo==='despesa'),'valor')};});
 const herdTrend=Array.from({length:6},(_,i)=>{const d=new Date();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-(5-i));return {label:new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(d).replace('.',''),value:(a.data||[]).filter(x=>x.sistema!=='leite'&&x.criado_em?.slice(0,7)<=d.toISOString().slice(0,7)).length};});
 return <AppShell farm={farm} active="Início"><Heading eyebrow={`Visão geral · ${label}`} title="Sua fazenda, em perspectiva." aside={<span className="date-pill">{label}</span>}/>
 <section className="hero-card"><div className="hero-topline"><Icon name="spark" size={15}/> SUA PROPRIEDADE EM FOCO</div><div className="hero-content"><span className="hero-location">{farm.cidade || 'Breu Branco'} · {farm.estado || 'PA'}</span><h2>{farm.nome}</h2><p>Uma visão clara do campo para decidir melhor todos os dias.</p><Link href="/painel/registrar" className="hero-button"><Icon name="plus" size={20}/> Registrar atividade <Icon name="arrow" size={16}/></Link></div><div className="hero-count"><span>REBANHO TOTAL</span><strong>{all.length}</strong><small>animais ativos</small></div></section>
 <div className="dashboard-overview"><section className="result-feature"><span className="feature-kicker"><Icon name="wallet" size={17}/> BALANÇO DA FAZENDA · {label.toUpperCase()}</span><span className="feature-label">Resultado do mês</span><strong>{current.length?money(sum(income,'valor')-sum(expense,'valor')):'—'}</strong><span className="feature-caption">{current.length?'Receitas menos despesas registradas':'Registre receitas e despesas para acompanhar'}</span><Link href="/painel/financeiro">Ver financeiro <Icon name="arrow" size={16}/></Link></section><div className="finance-mini-grid"><Stat label="Caixa disponível" value={tx.length?money(cash):'—'} detail="Valores já pagos"/><Stat label="Contas a pagar" value={pending.length?money(sum(pending,'valor')):'—'} detail={pending.length?`${pending.length} em aberto`:'Nenhuma em aberto'} tone={pending.length?'negative':''}/><Stat label="Valor do corte" value={money(valuation)} detail="Compras informadas"/></div></div>
 <div className="section-heading"><div><span className="overline">A FAZENDA EM NÚMEROS</span><h2>O que acontece no campo</h2></div><Link href="/painel/registrar" className="section-heading-link">+ Registrar</Link></div>
 <div className="herd-split"><Link href="/painel/rebanho" className="herd-feature herd-feature-beef"><div><span className="herd-eyebrow">01 / GADO DE CORTE</span><Icon name="arrow" size={18}/></div><strong>{beef.length}</strong><span>animais ativos</span><small>{l.data?.length??0} lotes ativos · acompanhar rebanho</small></Link><Link href="/painel/leite" className="herd-feature herd-feature-dairy"><div><span className="herd-eyebrow">02 / ATIVIDADE LEITEIRA</span><Icon name="arrow" size={18}/></div><strong>{dairy.length}</strong><span>animais ativos</span><small>{m.data?.length?`${number(milkTotal,1)} L produzidos no mês`:'Produção do mês ainda não registrada'}</small></Link></div>
 <div className="overview-grid"><Card title="Atividade da fazenda"><div className="overview-items"><Link href="/painel/rebanho"><Icon name="herd"/><span><strong>{l.data?.length??0} lotes ativos</strong><small>Gado de corte</small></span><Icon name="arrow" size={16}/></Link><Link href="/painel/pesagens"><Icon name="scale"/><span><strong>{w.data?.length?'Pesagens registradas':'Sem pesagens'}</strong><small>Acompanhe a evolução</small></span><Icon name="arrow" size={16}/></Link><Link href="/painel/leite"><Icon name="milk"/><span><strong>{m.data?.length?`${number(milkTotal,1)} L no mês`:'Sem produção no mês'}</strong><small>Atividade leiteira</small></span><Icon name="arrow" size={16}/></Link></div></Card><Card title="Alertas da fazenda">{alerts.length?alerts.map(x=><p className="alert-row" key={x.nome}><Icon name="alert" size={17}/>{x.nome}: {number(Number(x.quantidade_atual),1)} restantes</p>):<Empty title="Tudo em dia por aqui" description="Quando algum item atingir o estoque mínimo, avisaremos neste espaço."/>}<Link className="text-link" href="/painel/estoque">Ver estoque <Icon name="arrow" size={15}/></Link></Card></div>
 <div className="two-col dashboard-charts"><Card className="chart-card" title="Receitas e despesas"><p className="card-subtitle">Últimos seis meses · lançamentos reais</p><MonthlyChart months={months}/><Link className="text-link" href="/painel/financeiro">Explorar financeiro <Icon name="arrow" size={15}/></Link></Card><Card className="chart-card" title="Evolução do corte"><p className="card-subtitle">Animais cadastrados ao longo dos meses</p><TrendChart points={herdTrend.some(x=>x.value)?herdTrend:[]} unit="cabeças"/><Link className="text-link" href="/painel/rebanho">Ver animais de corte <Icon name="arrow" size={15}/></Link></Card></div>
 </AppShell>;
}
